### ISSUE TITLE
Uploaded image isn't showing up in the RB Submission Gallery

### ISSUE THREAD

**Issue by ngjo** [DoSomething/phoenix-next#125]
_BUG_
-------------------
**Current Behavior**
On https://next.dosomething.org/campaigns/teens-for-jeans/action when trying to RB, the uploaded image doesn't show up after hitting "Submit"

**Desired Behavior**
When you submit a photo and other RB info, it shows up under the uplaoder

**Steps to Replicate**
1. Go to https://next.dosomething.org/campaigns/teens-for-jeans/action
2. Try to upload a RB -- fill in all the info
3. It doesn't load

**Why This Matters**
So folks can see their RBs in the submission gallery

**Relevant Screenshots + Links**
![screen shot 2017-04-05 at 5 31 35 pm](https://cloud.githubusercontent.com/assets/2658867/24727982/166b8354-1a26-11e7-8b09-9cc3834322e2.png)

**Comment by weerd** [comment]
@ngjo ok, so it looks like [these items got added for analytics data tracking](https://github.com/DoSomething/phoenix-next/blob/17f82e2b7daad14991f684b7d113006582a01201/resources/assets/components/ReportbackItem/index.js#L11-L13) assuming they'd be present for all ReportbackItems, but that's definitely not the case for RB Items in the gallery; there is no reactions data passed to them, since only the member that submitted those will see them. I'll pop an a quick update so it can help unblock testing the uploader!
