### ISSUE TITLE
📝 "Big" refactor check list

### ISSUE THREAD

**Issue by itsjoekent** [DoSomething/phoenix-next#407]
- [x] Switch default export on all index.js files to the container instead of the component file. 
- [ ] ~~Move all prop types to Flow, export them from a separate folder~~
- [x] Move all containers in the container folder to component folders
- [ ] Consider parsing Markdown in PHP to help reduce the weight of adding parsing libs on the JS side Refs #416
- [x] We made a [good step forward](https://github.com/DoSomething/phoenix-next/pull/409) in ensuring signup data tracking is consistent, but the markup is still mixed throughout the codebase. Let's tidy that up.

**Comment by weerd** [comment]
@DFurnes thoughts on first item? @itsjoekent and I were discussing this a bit. We typically want the container for a component and not the component itself. It's more convenient but might also obscure implementation a bit since it's not the case for all components, so not always sure the default export is the component or the container when importing...

**Comment by DFurnes** [comment]
Yeah, I'm into that since it optimizes for the "common" use case. 👍

**Comment by itsjoekent** [comment]
updated this for signup markup refactoring

**Comment by weerd** [comment]
Closing this; most was address and what was not is no longer being considered or can become it's own ticket.
